[SDK-2190] Updated token for Stale GHA
BranchMetrics/android-branch-deep-linking-attribution pull request #1151
Opened 2023-12-06 22:26 UTC by nsingh-branch

## Reference
SDK-2190 -- Fix Stale GitHub Action

## Description
The current repo-token provided does not have the proper permissions for commenting on and adding labels to issues. To fix this, we can provide the repo's github.token, which would be the default for this action.

## Testing Instructions
Run the GitHub action and observe if the result is successful. 

## Risk Assessment [`LOW`]

- [x] I, the PR creator, have tested — integration, unit, or otherwise — this code.

## Reviewer Checklist (To be checked off by the reviewer only)

- [ ] JIRA Ticket is referenced in PR title.
- Correctness & Style
    - [ ] Conforms to [AOSP Style Guides](https://source.android.com/setup/contribute/code-style)
    - [ ] Mission critical pieces are documented in code and out of code as needed.
- [ ] Unit Tests reviewed and test issue sufficiently.
- [ ] Functionality was reviewed in QA independently by another engineer on the team.

cc @BranchMetrics/saas-sdk-devs for visibility.

2023-12-19 04:53 UTC, JagadeeshKaricherla-branch commented on .github/workflows/stale.yml
> +        repo-token: ${{ github.token }}
If it’s default, no need to set it again explicitly.
`repo-token: ${{ github.token }}`  can be removed.

Also, stale action is at v9 now.

2024-01-02 21:16 UTC, gdeluna-branch requested changes
Please update with Jagadeesh's suggestions

2024-01-02 22:04 UTC, nsingh-branch commented
> Please update with Jagadeesh's suggestions

Just made the requested changes

2024-01-09 19:17 UTC, gdeluna-branch approved these changes

2024-02-15 21:26 UTC, merged