[INTENG-13319] IntegrationValidator should read value from String Resource
BranchMetrics/android-branch-deep-linking-attribution pull request #923
Opened 2021-08-03 06:12 UTC by msiddiq-branch

## Reference
[INTENG-13319](https://branch.atlassian.net/browse/INTENG-13319) String Resource not recognised by IntegrationValidator

## Description
When uri scheme or app.link are placed under string resource IntegrationValidator failed to validate integration, have made created helper function to fetch resource based on resource id and pass this value to the validator.

## Testing Instructions
Step 1: Go to the manifest file and replaace URI scheme/app links string to string resource id
Step 2: Under MainActivity->Enable validator  `IntegrationValidator.validate(MainActivity.this);`
Step 3: Observe that IntegrationValidator should pass URI/app link test

## Risk Assessment [`LOW`]

- [ ] I, the PR creator, have tested — integration, unit, or otherwise — this code.

## Reviewer Checklist (To be checked off by the reviewer only)

- [ ] JIRA Ticket is referenced in PR title.
- Correctness & Style
    - [ ] Conforms to [AOSP Style Guides](https://source.android.com/setup/contribute/code-style)
    - [ ] Mission critical pieces are documented in code and out of code as needed.
- [ ] Unit Tests reviewed and test issue sufficiently.
- [ ] Functionality was reviewed in QA independently by another engineer on the team.

2021-08-10 11:26 UTC, bklastaitis-branch requested changes
Admittedly, we haven't followed this very strictly in the past, but we should add tests whenever adding any new features or fixing bugs. Unit tests (not android tests) might suffice in this case, though I'm not 100% sure (whenever possible unit tests should be preferred over android tests)

2021-08-10 11:26 UTC, bklastaitis-branch commented on Branch-SDK/src/main/java/io/branch/referral/validators/BranchIntegrationModel.java
> +                return context.getResources().getString(Integer.parseInt(resourceIdArr[1].replace("0x",""),16));
I know this is just a validator but this code looks very fragile, e.g. is it always base 16 and contains "0x"? If so, perhaps you can leave a comment saying so and/or giving examples?

Better yet, you could add a couple try/catches and rethrow the exception with the appropriate exception message (e.g. "could not read the string resource X").

2021-08-10 11:26 UTC, bklastaitis-branch commented on Branch-SDK/src/main/java/io/branch/referral/validators/BranchIntegrationModel.java
> +            String resourceIdArr[] = stringWithIdValue.split(" ");
C style declaration, replace with `String[] resourceIdArr`. In general please see what lint says and apply good judgement if you are ignoring it/add explanation.

2021-08-10 11:26 UTC, bklastaitis-branch commented on Branch-SDK/src/main/java/io/branch/referral/validators/BranchIntegrationModel.java
> +    public String getStringResource(String stringWithIdValue){
Formatting should follow code style, i.e. white space before the open curly bracket on this line, follow the same guideline on all the other places where open brackets are used. Similarly, in the `if` statements leave a space before the bracket and before each condition and before each equals sign. E.g. `if(context!=null && resourceIdArr!=null && resourceIdArr.length==2){` -> `if ( context != null && resourceIdArr != null && resourceIdArr.length == 2 ) {`

2021-08-10 11:26 UTC, bklastaitis-branch commented on Branch-SDK/src/main/java/io/branch/referral/validators/IntegrationValidator.java
> +                            if (uriPath != null && uriPath.equals(integrationModel.getStringResource(hosts.optString(i)))) {
handle the case when `hosts.optString(i)` returns `null`

2021-08-10 11:26 UTC, bklastaitis-branch commented on Branch-SDK/src/main/java/io/branch/referral/validators/IntegrationValidator.java
> +                if (domainName.equals(integrationModel.getStringResource(host))) {
At this point we don't know if `host` is a string resource or the actual string, so we should either rename the method to something like `maybeExtractStringResource` or add another util method to test if it is indeed a string resource and only then pass it your new method `getStringResource`.

2021-10-01 19:34 UTC, closed without merging

2021-10-01 19:34 UTC, agerstner-branch commented
We ended up doing this a different way.